name: CI Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 23
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '23'

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Post-build message
        if: always()
        run: echo "This will run regardless of the outcome."

      - name: Success message
        if: success()
        run: echo "Build, Dependencies setup, and Tests were successful!"

      - name: Failure message
        if: failure()
        run: echo "Build, Dependencies setup, or Tests failed."
